---
title: "Word Relationships"
author: "Shale"
date: "5/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr) #text analysis in R
library(pdftools)
library(lubridate) #working with date data
library(tidyverse)
library(tidytext)
library(readr)
library(quanteda)
library(readtext) #quanteda subpackage for reading pdf
library(quanteda.textstats)
library(quanteda.textplots)
library(ggplot2)
library(forcats)
library(stringr)
library(quanteda.textplots)
library(widyr)# pairwise correlations
library(igraph) #network plots
library(ggraph)
library(here)
```

# Import Data

```{r}
files <- list.files(path = here("data"), pattern = "^EPA")

#ej_reports <- lapply(files, pdf_text)

ej_pdf <- readtext(file = here("data", "EPAEJ*"), 
                   docvarsfrom = "filenames", 
                   docvarnames = c("type", "year"),
                   sep = "_")

#creating an initial corpus containing our data
epa_corp <- corpus(x = ej_pdf, text_field = "text" )
summary(epa_corp)
```

## Cleaning Data

```{r}
# Adding some additional, context-specific stop words to stop word lexicon
more_stops <- c("2015","2016", "2017", "2018", "2019", "2020", "www.epa.gov", "https")
add_stops <- tibble(word = c(stop_words$word, more_stops)) 
stop_vec <- as_vector(add_stops)
```

```{r}
# tokenization and cleaning
tokens <- tokens(epa_corp, remove_punct = TRUE)

toks1 <- tokens_select(tokens, min_nchar = 3) %>% 
  tokens_tolower() %>% 
  tokens_remove(pattern = (stop_vec))

dfm <- dfm(toks1)
```

## Relationship Analysis

```{r}
# bigrams
toks2 <- tokens_ngrams(toks1, n=2)
dfm2 <- dfm(toks2)
dfm2 <- dfm_remove(dfm2, pattern = c(stop_vec))
freq_words2 <- textstat_frequency(dfm2, n=20)
freq_words2$token <- rep("bigram", 20)
```

```{r}
# trigrams
toks3 <- tokens_ngrams(toks1, n=3)
dfm3 <- dfm(toks3)
dfm3 <- dfm_remove(dfm3, pattern = c(stop_vec))
freq_words3 <- textstat_frequency(dfm3, n=20)
freq_words3$token <- rep("trigram", 20)
```

```{r}
freq_words2
freq_words3
```

**The two tables above show the most common bigrams and trigrams in the EPAEJ Reports. A comparison of most common bigrams and trigrams shows that **

## Correlation Network

```{r}
#convert to tidy format and apply my stop words
raw_text <- tidy(epa_corp)

#Distribution of most frequent words across documents
raw_words <- raw_text %>%
  mutate(year = as.factor(year)) %>%
  unnest_tokens(word, text) %>%
  anti_join(add_stops, by = 'word') %>%
  count(year, word, sort = TRUE)

#number of total words by document  
total_words <- raw_words %>% 
  group_by(year) %>% 
  summarize(total = sum(n))

report_words <- left_join(raw_words, total_words)

par_tokens <- unnest_tokens(raw_text, output = paragraphs, input = text, token = "paragraphs")

par_tokens <- par_tokens %>%
 mutate(par_id = 1:n())

par_words <- unnest_tokens(par_tokens, output = word, input = paragraphs, token = "words") %>% 
  anti_join(add_stops, by = 'word')
```

```{r}
word_cors <- par_words %>% 
  add_count(par_id) %>% 
  filter(n >= 50) %>% 
  select(-n) %>%
  pairwise_cor(word, par_id, sort = TRUE)

comm_cors <- word_cors %>% 
  filter(item1 == "community")
```

Chart:

```{r}
comm_cors %>% 
  top_n(9) %>%
  ungroup() %>%
  mutate(item1 = as.factor(item1),
  name = reorder_within(item2, correlation, item1)) %>%
  ggplot(aes(y = name, x = correlation, fill = item1)) + 
  geom_col(show.legend = FALSE) +
  facet_wrap(~item1, ncol = 2, scales = "free")+
  scale_y_reordered() +
  labs(y = NULL,
         x = NULL,
         title = "Correlations with key words",
         subtitle = "EPA EJ Reports")
```

Network Visualization: 

```{r}
comm_cors  %>%
  filter(correlation > .15) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation, edge_width = correlation), edge_colour = "purple") +
  geom_node_point(size = 5) +
  geom_node_text(aes(label = name), repel = TRUE, 
                 point.padding = unit(0.2, "lines")) +
  theme_void()
```

## Keyness Analysis Function

```{r}
key_gram <- function(r1, r2, ngram, stopwd = stop_vec) {
  tokens <- tokens(epa_corp, remove_punct = TRUE)
  toks1  <- tokens_select(tokens, min_nchar = 3)
  toks1  <- tokens_tolower(toks1)
  toks1  <- tokens_remove(toks1, pattern = (stop_vec))
  toks1  <- tokens_ngrams(toks1, n=ngram)
  dfm    <- dfm(toks1)
  
  keyness <- textstat_keyness(dfm, target = 2)
  textplot_keyness(keyness)
}

key_gram("EPA", 2020, 2)
```

